/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FlaggedRouteImport } from './routes/flagged'
import { Route as FailureQueueRouteImport } from './routes/failure-queue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TracesIndexRouteImport } from './routes/traces/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons/$lessonId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FlaggedRoute = FlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => rootRouteImport,
} as any)
const FailureQueueRoute = FailureQueueRouteImport.update({
  id: '/failure-queue',
  path: '/failure-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TracesIndexRoute = TracesIndexRouteImport.update({
  id: '/traces/',
  path: '/traces/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/failure-queue': typeof FailureQueueRoute
  '/flagged': typeof FlaggedRoute
  '/settings': typeof SettingsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/': typeof LessonsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/failure-queue': typeof FailureQueueRoute
  '/flagged': typeof FlaggedRoute
  '/settings': typeof SettingsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons': typeof LessonsIndexRoute
  '/traces': typeof TracesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/failure-queue': typeof FailureQueueRoute
  '/flagged': typeof FlaggedRoute
  '/settings': typeof SettingsRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/': typeof LessonsIndexRoute
  '/traces/': typeof TracesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/failure-queue'
    | '/flagged'
    | '/settings'
    | '/lessons/$lessonId'
    | '/lessons/'
    | '/traces/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/failure-queue'
    | '/flagged'
    | '/settings'
    | '/lessons/$lessonId'
    | '/lessons'
    | '/traces'
  id:
    | '__root__'
    | '/'
    | '/failure-queue'
    | '/flagged'
    | '/settings'
    | '/lessons/$lessonId'
    | '/lessons/'
    | '/traces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FailureQueueRoute: typeof FailureQueueRoute
  FlaggedRoute: typeof FlaggedRoute
  SettingsRoute: typeof SettingsRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  TracesIndexRoute: typeof TracesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flagged': {
      id: '/flagged'
      path: '/flagged'
      fullPath: '/flagged'
      preLoaderRoute: typeof FlaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failure-queue': {
      id: '/failure-queue'
      path: '/failure-queue'
      fullPath: '/failure-queue'
      preLoaderRoute: typeof FailureQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traces/': {
      id: '/traces/'
      path: '/traces'
      fullPath: '/traces/'
      preLoaderRoute: typeof TracesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FailureQueueRoute: FailureQueueRoute,
  FlaggedRoute: FlaggedRoute,
  SettingsRoute: SettingsRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  TracesIndexRoute: TracesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
