"""Initial schema with traces and lessons tables

Revision ID: 8ef2ebd56eb6
Revises: 
Create Date: 2026-03-05 15:01:10.747571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ef2ebd56eb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('task_context', sa.Text(), nullable=False),
    sa.Column('state_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_taken', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('lesson_text', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(384), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_validated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source_trace_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lessons_agent_domain', 'lessons', ['agent_id', 'domain'], unique=False)
    op.create_index(op.f('ix_lessons_agent_id'), 'lessons', ['agent_id'], unique=False)
    op.create_index('ix_lessons_confidence', 'lessons', ['confidence'], unique=False)
    op.create_index('ix_lessons_embedding_hnsw', 'lessons', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_lessons_source_trace_id'), 'lessons', ['source_trace_id'], unique=False)
    op.create_table('traces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=255), nullable=False),
    sa.Column('trace_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('span_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_agent_id'), 'traces', ['agent_id'], unique=False)
    op.create_index('ix_traces_status_created', 'traces', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_traces_status_created', table_name='traces')
    op.drop_index(op.f('ix_traces_agent_id'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_lessons_source_trace_id'), table_name='lessons')
    op.drop_index('ix_lessons_embedding_hnsw', table_name='lessons', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_lessons_confidence', table_name='lessons')
    op.drop_index(op.f('ix_lessons_agent_id'), table_name='lessons')
    op.drop_index('ix_lessons_agent_domain', table_name='lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
